### PR TITLE
Implementing Gulp Task Runner

### PR DESCRIPTION
**Pull request by joaovsilva**
Hello! I just implemented Gulp with a single task, which compiles SASS files into CSS. But it's just a matter of time for me to improve more the repo ;)

Thanks!

### CODE REVIEW

**Comment by raphamorim** [comment]
@afonsopacifer @willianjusten anyone can check this changes?

**Comment by willianjusten** [comment]
What? Why Sass?

We're using Stylus as our css pre-processor...

And we don't need Gulp to automate our tasks, we can add on package.json like we did with another commands before.

**Comment by joaovsilva** [comment]
Why SASS? Well I think everybody here is working on a repository, for not just us, but for PEOPLE like us? Right? Well in my opinion we need to cover all kind of different type of environments.

Using only Stylus we're letting go a considered number of people, that like to use any other Preprocessors, like SASS and LESS. The fact that SASS is in the project doesn't mean it is REQUIRED, we are only adding an OPTIONAL feature. So people who likes to work with SASS, can do it normally, the same goes to LESS.

And about Gulp, it's okay about it. If you think of a better solution, I'm all here to listening, okay? Just explain what you want for me to understand... @willianjusten

**Comment by afonsopacifer** [comment]
@joaovsilva Thank you for contributing, but
The stylus is only to better organize the style of the website,
he was chosen to be part of the  NodeJS stack.

The "core" project is not the style, but is to encourage people to adhere to the Write Code Every Day, so it does not become necessary to have more pre-processor options.

Mai again, thank you for contributing, but at the moment we do not think interesting implement another preprocessor. :)

**Pull request closed without merging**
